name: Code Verification

on:
  workflow_dispatch:     # Puedes ejecutarlo manualmente
  pull_request:          # Se ejecuta en PR (opcional, puedes quitarlo)

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      contents: read      # Solo para leer el repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # versi√≥n nueva, no deprecada

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run Tests
        run: mvn test -B
