name: 01 - Main CI / Security Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  build:
    name: Construcción
    uses: ./.github/workflows/build.yml
    secrets: inherit

  sca:
    name: Anaálisis de composición
    needs: build
    uses: ./.github/workflows/analisis-composicion.yml
    secrets: inherit

  sast:
    name: Análisis estático
    needs: build
    uses: ./.github/workflows/analisis-estatico.yml
    secrets: inherit
    
  docker:
    name: Contruir imagen de Docker
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    
  container-image-scan:
    name: Escaneo de la imagen de Docker
    needs: docker
    uses: ./.github/workflows/scan-contenedor.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}

  dast:
    name: Test
    needs: docker
    uses: ./.github/workflows/test-dast.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
